name: Buffer CI

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install build-essential

    - name: Build
      run: make 

    - name: Test 
      run: make check

  release:
    name: Release
    runs-on: ubuntu-latest

    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install GCC and Zip
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential

      - name: Build
        run: |
          make
          cd build
          zip buffer.zip test

      - name: Run The Test
        run: make check

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Version
          files: build/buffer.zip  